spring:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        show-sql: true
        ddl-auto: create
        format_sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/KopMorning
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver