spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/kopmorning
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 0913
  jpa:
    show-sql: true # SQL ??? ??? ??? ? ??
    generate-ddl: true # ?????? ?? ? DDL ?? ?? ??
    properties:
      hibernate:
        show-sql: true #Hibernate? ???? SQL ??? ??? ??? ? ??
        ddl-auto: create #Hibernate? DDL? ??? ???? ??
        format_sql: true #SQL ??? ?? ?? ??? ? ??
jwt:
  secret: