# todo : 추후에 배포 서버로 변경
name: 서버 배포

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create application-prod-secret.yml
        run: |
          echo "$APPLICATION_PROD_SECRET_YML" > src/main/resources/application-secret.yml
        working-directory: backend
        env:
          APPLICATION_PROD_SECRET_YML: ${{ secrets.APPLICATION_PROD_SECRET_YML }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grant execute permission for gradlew
        working-directory: backend
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -i -Dspring.profiles.active=prod
        working-directory: backend

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kopmorning:latest .
        working-directory: backend

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kopmorning:latest
        working-directory: backend

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with docker-compose on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << EOF
            docker ps -q
          
            docker ps -aq
          
            cd ~/myapp
          
            git remote set-url origin git@github.com:junho767/Kopmorning.git
            git pull origin develop || echo "Git pull failed or no repo cloned"

            cat <<EOT > .env
              $DOCKER_ENV_FILE
          EOT
  
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/kopmorning:latest
          
          docker compose down || true
          
          docker compose up -d --build
          EOF
        env:
          DOCKER_ENV_FILE: ${{ secrets.DOCKER_ENV_FILE }}
